### ISSUE TITLE
Align CEP section with the Tour Guide App 

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/docs.TourGuide#19]
CEP section on the tour guide needs to be aligned with the Tour Guide Application example

**Comment by jmcanterafonseca** [comment]
closing this. CEP Proton has been discontinued

**Comment by fgalan** [comment]
fiware-cep in StackOverflow stills mentioning Proton:

![imagen](https://user-images.githubusercontent.com/1534240/40113027-48e21696-5908-11e8-8040-5641b0a94879.png)

This should be fixed... in some way. Maybe with a more neutral label description, removing Proton mentions.
