### ISSUE TITLE
Remove NGSIv1 references in the Tour Guide

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/docs.TourGuide#64]
once Context Providers are fully supported in NGSIv2, any reference to NGSIv1 shall be dropped.

In the meantime perhaps we can remove all NGSIv1 and leave only the context provider related content. Or even drop it now as @jason-fox is working on 

https://github.com/Fiware/tutorials.Context-Providers 

@fgalan opinions?

**Comment by fgalan** [comment]
I fully support removing any reference to NGSIv1 in any piece of documentation, Tour Guide included of course :) Please, go ahead. Put me in CC in the PR doing so if you want me to have a look to the changes.

**Comment by jmcanterafonseca** [comment]
fixed.
